# Generated by Django 4.2.9 on 2024-05-15 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.TextField(verbose_name='형식')),
                ('purpose', models.TextField(verbose_name='목적')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('bookmark', models.BooleanField(default=False, verbose_name='즐겨찾기')),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='writings.writing')),
            ],
        ),
    ]
